server:
  port: 9001

spring:
  application:
    name: gateway-server
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:RefreshTokendb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cloud:
    gateway:
      routes:
        - id: user-command-NoAuthentication
          uri: http://172.18.0.4:8081
          predicates:
            - Path=/api/user/command/login, /api/user/command/join
          filters:
            - NoAuthenticationFilter

        - id: user-query-NoAuthentication
          uri: http://172.18.0.5:8082
          predicates:
            - Path=/api/user/query/findUserId, /api/user/query/availableUserId
          filters:
            - NoAuthenticationFilter

        - id: user-command
          uri: http://172.18.0.4:8081
          predicates:
            - Path=/api/user/command/**,
          filters:
            - AuthenticationFilter

        - id: user-query
          uri: http://172.18.0.5:8082
          predicates:
            - Path=/api/user/query/**
          filters:
            - AuthenticationFilter

        - id: pet-TotalAuthentication
          uri: http://172.18.0.8:3000
          predicates:
            - Path=/pet/**
          filters:
            - TotalAuthenticationFilter

        - id: image
          uri: http://172.18.0.10:7099
          predicates:
            - Path=/image/**
          filters:
            - AuthenticationFilter

jwt:
  properties:
    secret: 123
    access-token-expiration-seconds: 60 # 900 10?
    refresh-token-expiration-seconds: 180 # 3600 1??
    token-prefix: Bearer

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/