server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  properties:
    secret: 123
    access-token-expiration-seconds: 60 # 900 15분
    refresh-token-expiration-seconds: 180 # 1209600 14일
    token-prefix: Bearer
  response:
    access-token-header-name: Authorization
    refresh-token-header-name: Refresh-Token