server:
  port: 7099

spring:
  data:
    mongodb:
      host: 172.18.0.11
      port: 27017
      authentication-database: admin
      username: u
      password: p
      database: comepethome

cloud:
  aws:
    s3:
      accessKey: a
      secretKey: s
      bucketName: comepethome-image
      region:  ap-northeast-2

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/