server:
  port: 8081

spring:
  main:
    lazy-initialization: false

  application:
    name: user-command-server
  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mariadb://172.18.0.6:3306/comepethome?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: u
    password: p

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: false
    baseline-on-migrate: true

jwt:
  properties:
    secret: 123
    access-token-expiration-seconds: 60 # 600 10분
    refresh-token-expiration-seconds: 180 # 3600 1시간
    token-prefix: Bearer

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/

test:
  id:
  pw:
  server-ip:
  port: