server:
  port: 8082

spring:
  application:
    name: user-query-server

  data:
    mongodb:
      host: 172.18.0.9
      port: 27017
      authentication-database: admin
      database: comepethome
      username: root
      password: admin

  flyway:
    enabled: false
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/