server:
  port: 8082

spring:
  application:
    name: user-query-server
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  properties:
    secret: 123
    access-token-expiration-seconds: 60 # 600 10분
    refresh-token-expiration-seconds: 180 # 3600 1시간
    token-prefix: Bearer

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/