create table users(
    id bigint generated by default as identity,
    user_id varchar(255),
    password varchar(255),
    access_token varchar(255),
    refresh_token varchar(255),
    nick_name varchar(100),
    image_url varchar(255),
    create_at date,
    update_at date,
    primary key (id)
);

insert into users (user_id, password, nick_name) values ('ryu', '1234', '류현우');
